import os

USERNAME = os.getenv("SHIMARIN_USERNAME", "")
PASSWORD = os.getenv("SHIMARIN_PASSWORD", "")
SERVER_ENDPOINT = os.getenv("DEEPDANBOORYU_SERVER_ENDPOINT", "http://localhost:9090")
SERVER_PORT = int(os.getenv("DEEPDANBOORYU_SERVER_PORT", 80))
