import os

USERNAME = os.getenv("DEEPDANBOORYU_USERNAME")
PASSWORD = os.getenv("DEEPDANBOORYU_PASSWORD")
SERVER_ENDPOINT = os.getenv("DEEPDANBOORYU_SERVER_ENDPOINT")
SERVER_PORT = int(os.getenv("DEEPDANBOORYU_SERVER_PORT", 80))
